site_name: The Privacy Guide  
site_description: A definitive guide to claim back your privacy online
nav:
  - About the Guide:
    - Introduction: index.md
  - Guides:
    - "Overview": guides/index.md
    - "1. Securing Your Online Accounts": guides/1_Securing_Accounts/index.md
  - Glossary:
      - A-Z: glossary/index.md
theme:
  name: material
  features:
    - tabs
  font: false
  social: /docs/logo.svg
  custom_dir: theme
extra_css:
  - custom.css
extra_javascript:
  - player.js
  - external.js
  - download.js
plugins:
  - search
  - macros
  - pdf-export:
      theme_handler_path: pdf-theme-handler.py
      enabled_if_env: ENABLE_PDF_EXPORT
      media_type: print
      verbose: true
  - exclude:
      glob: []
markdown_extensions:
  - attr_list
  - meta
  - admonition
  - markdown_include.include
  - toc:
      permalink: "#"
      baselevel: 2
      separator: "_"
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
use_directory_urls: true
copyright: Copyright © 2020 The Privacy Guide
